# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.cache/wt [current_project]
set_property parent.project_path C:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.srcs/sources_1/imports/Datapath/SL2.vhd
  C:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.srcs/sources_1/imports/regfile_sources/regfile.vhd
  C:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.srcs/sources_1/imports/ergasia/R32we.vhf
  C:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.srcs/sources_1/imports/ergasia/R32.vhf
  C:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.srcs/sources_1/imports/Datapath/MUX_3to1_32x.vhd
  C:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.srcs/sources_1/imports/test_project/mux_2in1_5bit.vhd
  C:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.srcs/sources_1/imports/Memories/imem_rom_64x32_SimpleExample1.vhd
  C:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.srcs/sources_1/imports/test_project/EXTsz.vhd
  C:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.srcs/sources_1/imports/Memories/dmem_ram_32x32.vhd
  C:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.srcs/sources_1/imports/regfile_sources/CNTR_fsm.vhd
  C:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.srcs/sources_1/imports/regfile_sources/CNTR_comb.vhd
  C:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.srcs/sources_1/imports/Datapath/CNTR_aux.vhd
  C:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.srcs/sources_1/imports/Datapath/BUS32_aux.vhd
  C:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.srcs/sources_1/imports/regfile_sources/ALU3.vhd
  C:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.srcs/sources_1/imports/test_project/ADD.vhd
  C:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.srcs/sources_1/imports/ergasia/datapath.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.srcs/constrs_1/imports/regfile_sources/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/Valia/Downloads/5o/VHDL/ergasia/askisiVHDL/askisiVHDL.srcs/constrs_1/imports/regfile_sources/constraints.xdc]


synth_design -top datapath -part xc7z020clg484-1


write_checkpoint -force -noxdef datapath.dcp

catch { report_utilization -file datapath_utilization_synth.rpt -pb datapath_utilization_synth.pb }
